# ConfigMap of API with connection
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-consolidation-config
data:
  Cashflow__UrlBase: "http://cashflowapi-service.default.svc.cluster.local"
---
# Deployment of cashflowapi with dependency on db postgresql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consolidationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolidationapi
  template:
    metadata:
      labels:
        app: consolidationapi
    spec:
      containers:
      - name: consolidationapi
        image: docker.io/netogan/consolidationapi:latest
        ports:
        - containerPort: 90
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        envFrom:
        - configMapRef:
            name: app-consolidation-config
        livenessProbe:
          httpGet:
            path: /api/health
            port: 90
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 90
          initialDelaySeconds: 5
          periodSeconds: 10
---
#Service of cashflowapi
apiVersion: v1
kind: Service
metadata:
  name: consolidationapi-service
spec:
  selector:
    app: consolidationapi
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 90